#!/bin/bash

PUID=${PUID:-999}
PGID=${PGID:-$PUID}

usermod -o -u "$PUID" user
groupmod -o -g "$PGID" user

if [ ! -f "/opt/seafile/crontab" ]; then
    echo "copy crontab"
    cp /opt/crontab /opt/seafile
fi

chown $PUID:$PGID /opt/seafile/
chown $PUID:$PGID /opt/seafile/crontab
chown $PUID:$PGID /opt/service_seafile.sh

cron /opt/seafile/crontab &

/bin/bash /opt/service_seafile.sh $1
